nelmio_cors:
  defaults:
    allow_origin: ['http://localhost:4200']
    allow_credentials: true
    allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
    allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
    expose_headers: ['Set-Cookie']
    max_age: 3600

  paths:
    '^/api/':
      allow_origin: ['http://localhost:4200']
      allow_credentials: true
      allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
      allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
      expose_headers: ['Set-Cookie']
