nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:4200']
        allow_methods: ['POST', 'GET', 'PUT', 'DELETE', 'OPTIONS']
        allow_headers: ['Content-Type', 'Authorization']
        allow_credentials: true
        max_age: 3600
    paths:
        '^/api/':
            allow_origin: ['http://localhost:4200']
            allow_methods: ['POST', 'GET', 'PUT', 'DELETE', 'OPTIONS']
            allow_headers: ['Content-Type', 'Authorization']
            allow_credentials: true
